### ISSUE TITLE
Links in the docs point to your local filesystem

### ISSUE THREAD

**Issue by anka-213** [hasura/eff#4]
Every link that points outside this package points to the local copy on your filesystem instead of for example hackage docs. For example, the link to `MonadTransControl` [here](https://hasura.github.io/eff/Control-Effect.html#v:controlT) points to `file:///Users/alexis/.cabal/store/ghc-8.8.1/mnd-cntrl-1.0.2.3-b06f566f/share/doc/html/Control-Monad-Trans-Control.html#t:MonadTransControl`.

This flag might work: https://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-flag---html-location

If not, just close or ignore the issue, since it's a minor issue and not worth wasting a lot of time on. (And it might be impossible to fix: https://stackoverflow.com/questions/57916341/how-to-instruct-haddock-to-link-to-hackage-documentation-for-hackage-packages)

**Comment by lexi-lambda** [comment]
You’re right, thanks for the report—previous versions of the docs I uploaded used the flag, but it looks like I screwed up the most recent time (since I’ve been uploading them by hand for now). I’ll be sure to fix this next time I push the docs.

**Comment by lexi-lambda** [comment]
This is now fixed. It’s of limited use, as the current version of the docs link to the docs for `base-4.14.0.0`, which doesn’t exist on Hackage, but the outgoing links to other packages work, at least.
